### PR TITLE
Update Julia link in readme

### PR DESCRIPTION
**Pull request by jeremejevs**
Reason: https://github.com/tomv564/LSP/pull/316

### CODE REVIEW

**Comment by tomv564** [comment]
Thanks, just realised we want to keep our own documentation section, but added the link to LSP-julia there.

**Comment by jeremejevs** [comment]
Spent the whole making Sublime work with Julia, and it's in a bit of a sad state, compared to VSC, but can be done. The necessary steps, as of writing this (will get better eventually):

1. Do `dev LanguageServer`, instead of `add LanguageServer`, as it requires modifications.
1. Once it's downloaded, go to `~/.julia/dev/LanguageServer` and apply these two patches:
https://github.com/julia-vscode/LanguageServer.jl/pull/380
https://github.com/julia-vscode/LanguageServer.jl/pull/387
1. Clone [my fork](https://github.com/jeremejevs/LSP-julia/tree/patch-1) of `LSP-julia` instead of the upstream until this is merged: https://github.com/randy3k/LSP-julia/pull/2

The instructions you've added need a slight adjustment: the bash script is located at `PATH_TO_JULIA_SERVER_PACKAGE/contrib/languageserver.sh`. If you install it the regular way, with `add`, then it gets placed somewhere like `~/.julia/packages/LanguageServer/SOME_HASH/contrib/languageserver.sh`, and if you install it with `dev` then it ends up in `~/.julia/dev/LanguageServer/contrib/languageserver.sh`.

**Comment by jwortmann** [comment]
I have recently set up the Julia language server on Windows and I want to add my experiences here:

The language server also requires to have the `SymbolServer` package installed to work. The currently not yet merged pull request julia-vscode/LanguageServer.jl#387 that you mentioned seems to automatically take this into account via that Shell script, but I guess it is only used on Linux/macOS (?) and would have no effect on Windows. Perhaps you want to add that information to the docs? For manual installation of the LanguageServer and SymbolServer you can use the following commands in the Julia REPL: 
```
import Pkg;
Pkg.add("LanguageServer")
Pkg.add("SymbolServer")
```
I use the following client settings for Julia in my `LSP.sublime-settings` file:
```json
"julials":
{
    "command": ["julia", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; using SymbolServer; server=LanguageServer.LanguageServerInstance(stdin,stdout,false); run(server);"],
    "scopes": ["source.julia"],
    "syntaxes": ["Packages/Julia/Julia.sublime-syntax"],
    "languageId": "julia",
    "enabled": true
}
```
Again, I believe what is currently written in the LSP documentation would not work on Windows.

If I don't use these settings and instead place the file from https://github.com/jeremejevs/LSP-julia/tree/patch-1 into a folder in my packages directory, it doesn't work at all for me:
```
LSP: no config found or enabled for view D:\path\to\file.jl
```

However, even with my settings the language server occasionally crashes when closing tabs or switching between tabs :confused:
I get this error log in the Sublime console:
```
Failure writing to stdout
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument

LSP: transport failed
```
I am not sure if this is a bug in the language server, in the LSP plugin or in my configuration, but the same sometimes happen with other language servers too, so my first guess would be that it is an issue within the LSP plugin.

**Comment by tomv564** [comment]
@jeremejevs great that you're contributing to LSP-julia, especially if things stabilise now after Julia 1.0!

@jwortmann besides the exception trace, can you help determine what caused the julia server to shut down? Perhaps turn on all the `log_*` LSP settings and try again?

**Comment by jwortmann** [comment]
I have recorded some crashes that happen when rearranging tabs and opening new files, but from the error logs I cannot really tell what is causing these issues. I also remember some crashes of the Fortran language server when closing files, but I just tested that and it doesn't seem to happen anymore.

Julia:
julia
<details><summary>relevant error log</summary>
<pre>
LSP: unloading session julials
LSP:  --> shutdown
LSP:  --> textDocument/didOpen
ERROR: KeyError: key "params" not found:
Stacktrace::
[1] getindex at .\dict.jl:478 [inlined]:
[2] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at C:\Users\Janos\.julia\packages\LanguageServer\NIueX\src\jsonrpc.jl:36:
[3] run(::LanguageServerInstance) at C:\Users\Janos\.julia\packages\LanguageServer\NIueX\src\languageserverinstance.jl:45:
[4] top-level scope at none:0:
LSP: LSP stdout process ended.
LSP: LSP stream logger stopped.
LSP: Couldn't determine project directory since no folders are open! Using D:\data\code\Julia as a fallback.
LSP: project path changed, ending existing sessions
LSP: new path = D:\data\code\Julia
LSP: unloading session julials
LSP:  --> shutdown
Failure writing to stdout
Traceback (most recent call last):
  File "C:\Users\Janos\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument
</pre>
</details>

TexLab (LaTeX):
texlab
<details><summary>error log 1</summary>
<pre>
LSP: unloading session texlab
LSP:  --> shutdown
thread 'tokio-runtime-worker-0' panicked at 'Unexpected response received', src\libcore\option.rs:1166:5:
stack backtrace::
0: <unknown>:
1: <unknown>:
2: <unknown>:
3: <unknown>:
4: <unknown>:
5: <unknown>:
6: <unknown>:
7: <unknown>:
8: <unknown>:
9: <unknown>:
10: <unknown>:
11: <unknown>:
12: <unknown>:
13: <unknown>:
14: <unknown>:
15: <unknown>:
16: <unknown>:
17: <unknown>:
18: <unknown>:
19: BaseThreadInitThunk:
20: RtlUserThreadStart:
thread 'main' panicked at 'the main future has panicked: Canceled', src\libcore\result.rs:1084:5:
stack backtrace::
0: <unknown>:
1: <unknown>:
2: <unknown>:
3: <unknown>:
4: <unknown>:
5: <unknown>:
6: <unknown>:
7: <unknown>:
8: <unknown>:
9: <unknown>:
10: BaseThreadInitThunk:
11: RtlUserThreadStart:
LSP:  --> textDocument/didOpen
LSP:LSP: LSP stream logger stopped.
 Failure writing to stdoutLSP stdout process ended.

Traceback (most recent call last):
  File "C:\Users\Janos\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 226, in write_stdin
    self.process.stdin.write(msgbytes)
OSError: [Errno 22] Invalid argument
</pre>
</details>

<details><summary>error log 2</summary>
<pre>
LSP: unloading session texlab
LSP:  --> shutdown
thread 'tokio-runtime-worker-0' panicked at 'Unexpected response received', src\libcore\option.rs:1166:5:
stack backtrace::
0: <unknown>:
1: <unknown>:
2: <unknown>:
3: <unknown>:
4: <unknown>:
5: <unknown>:
6: <unknown>:
7: <unknown>:
8: <unknown>:
9: <unknown>:
10: <unknown>:
11: <unknown>:
12: <unknown>:
13: <unknown>:
14: <unknown>:
15: <unknown>:
16: <unknown>:
17: <unknown>:
18: <unknown>:
19: BaseThreadInitThunk:
20: RtlUserThreadStart:
LSP:  --> textDocument/didOpen
Failure writing to stdout
Traceback (most recent call last):
  File "C:\Users\Janos\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 226, in write_stdin
    self.process.stdin.write(msgbytes)
OSError: [Errno 22] Invalid argument
</pre>
</details>

<details><summary>My LSP settings:</summary>
<pre>
{
    "auto_show_diagnostics_panel": false,
    "log_debug": true,
    "log_payloads": true,
    "log_stderr": true,
    "only_show_lsp_completions": true,
    "clients":
    {
        "fortls":
        {
            "command": ["fortls", "--lowercase_intrinsics", "--variable_hover"],
            "scopes": ["source.modern-fortran"],
            "syntaxes": ["Packages/Fortran/grammars/FortranModern.sublime-syntax"],
            "languageId": "fortran",
            "enabled": true
        },
        "julials":
        {
            "command": ["julia", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; using SymbolServer; server=LanguageServer.LanguageServerInstance(stdin,stdout,false); run(server);"],
            "scopes": ["source.julia"],
            "syntaxes": ["Packages/Julia/Julia.sublime-syntax"],
            "languageId": "julia",
            "enabled": true
        },
        "pyls":
        {
            "settings": {
                "pyls": {
                    "plugins": {
                        "mccabe": {
                            "enabled": false
                        },
                        "pyflakes": {
                            "enabled": false
                        },
                        "pylint": {
                            "enabled": false
                        }
                    }
                }
            },
            "enabled": true
        },
        "texlab":
        {
            "command": ["texlab"],
            "languages": [{
                "scopes": ["text.tex.latex"],
                "syntaxes": ["Packages/LaTeX/LaTeX.sublime-syntax"],
                "languageId": "latex"
            }, {
                "scopes": ["text.bibtex"],
                "syntaxes": ["Packages/LaTeX/Bibtex.sublime-syntax"],
                "languageId": "bibtex"
            }],
            "enabled": true
        }
    }
}
</pre>
</details>

**Comment by jwortmann** [comment]
After looking at the issue tracker, I am pretty sure those crashes happen due to #668, because I also don't use Sublime projects. It would be nice if we could find a fix for better handling of single files in LSP to prevent these crashes.

**Comment by tomv564** [comment]
Agree, #668 is the real cause of your issues. 

Julia server issue in your logs: LSP doesn't send any "params" member in the shutdown request payload, which breaks the Julia server (though I think spec allows it) (see https://github.com/julia-vscode/LanguageServer.jl/blob/cd7cfab06c04819ea9a1064a5ba4047e6f36a8d5/src/jsonrpc.jl#L36)

**Pull request merged**
