### PR TITLE
Organize our textdocument and workspace capabilities

### PR DESCRIPTION
**Pull request by rwols**
Organize our textdocument and workspace capabilities.

### CODE REVIEW

**Comment by tomv564** [comment]
The organisation and highlighting of missing capabilities is really great, but I'd like to know why need to send 'dynamicRegistration: false' in the first place - the absence should be "falsy" and back-wards compatible?

**Comment by rwols** [comment]
> the absence should be "falsy" and back-wards compatible?

You're right. I'll remove the explicitness after #689 is merged.

**Comment by rwols** [comment]
Now that #689 is merged I added colorProvider to the capabilities.

**Comment by tomv564** [comment]
I don't think this PR on the whole improves the initialisation params. The result has become harder to read, and we now have a bunch of function calls and typing just to provide constant dicts. It probably made more sense when there was some repetition with the dynamic registration property?

We probably also shouldn't use the codebase for documenting missing capabilities as the protocol will always continue adding more. We can use the wiki and users can open issues to help bring them to our attention.

**Comment by rwols** [comment]
Agreed.

**Pull request closed without merging**
