### PR TITLE
Support both SymbolInformation as well as DocumentSymbol for textDocument/documentSymbol

### LINKED ISSUE #519: Intelephense document symbols isn't working
When triggering the document symbols command no properties or methods are displayed.

* OSX 10.14 Intelephense v1.0.2
* Package Control
* Trigger LSP ```lsp_document_symbols```
* Log:

```
Traceback (most recent call last):
  File "/Users/carlos/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/symbols.py", line 70, in on_symbol_selected
    range = selected_symbol['location']['range']
KeyError: 'location'
```

### PR DESCRIPTION
**Pull request by rwols**
Should resolve #519. @carlevison, @jfcherng, could you take a look and see if this works?

### CODE REVIEW

**Comment by carlevison** [comment]
@rwols For some reason this stops LSP working for me, I don't see ```LSP initialized```when opening Sublime.

**Comment by rwols** [comment]
Strange. It seems to be working fine here. Are you sure you pulled my latest diff? Can you enable debug logging via `Preferences: LSP` in the command palette?

**Comment by carlevison** [comment]
Okay so I originally copied the changes myself after extracting the package but this time I removed it and cloned the branch and LSP is starting.

The error in the console has gone but I still don't see the method or property names.

I also noticed if I trigger ``` lsp_document_symbols```and then press <kbd>esc</kbd> to cancel the whole contents of the file is selected.

**Comment by jfcherng** [comment]
I could **successfully** do `textDocument/documentSymbol` with this patch (and the current `master` branch LSP).

> I also noticed if I trigger ` lsp_document_symbols`and then press esc to cancel the whole contents of the file is selected.

I could confirm this. After press ESC, ST selects the whole `class` codes in my case.

**Comment by predragnikolic** [comment]
Should we open up a new issue for this?
> I also noticed if I trigger ` lsp_document_symbols`and then press esc to cancel the whole contents of the file is selected.

Or we can add them to this pr?

```diff
diff --git a/plugin/symbols.py b/plugin/symbols.py
index 4d00e56..c6e553a 100644
--- a/plugin/symbols.py
+++ b/plugin/symbols.py
@@ -81,6 +81,9 @@ class LspDocumentSymbolsCommand(LspTextCommand):
         self.view.window().show_quick_panel(symbols, self.on_symbol_selected)
 
     def on_symbol_selected(self, symbol_index):
+        if symbol_index < 0:
+            return
+
         selected_symbol = self.symbols[symbol_index]
         try:
             range = selected_symbol['location']['range']
@@ -90,6 +93,6 @@ class LspDocumentSymbolsCommand(LspTextCommand):
             debug('could not recognize the type: expected either SymbolInformation or DocumentSymbol')
             return
         region = range_to_region(Range.from_lsp(range), self.view)
-        self.view.show_at_center(region)
+        self.view.show_at_center(region.begin())
         self.view.sel().clear()
-        self.view.sel().add(region)
+        self.view.sel().add(region.begin())

```

**Comment by rwols** [comment]
> Should we open up a new issue for this?

I consider this a separate issue, just want to get the bugs fixed for now.

**Pull request closed without merging**
