### PR TITLE
Replace undecodeable UTF-8 sequences by '?'

### PR DESCRIPTION
**Pull request by rwols**
There's nothing in the LSP spec about the encoding of the stderr stream (or in the case of the TCP transport the stdout stream). We're assuming UTF-8, which is a good choice I think, but if the encoding fails we can try UTF-16 as a last resort.

Related: #249

### CODE REVIEW

**Comment by rwols** [comment]
closing and reopening due to test flakiness

**Comment by tomv564** [comment]
We could also look at using `locale.getpreferredencoding` ? UTF-16 is perhaps only commonly seen on windows?

**Comment by rwols** [comment]
I really that idea, let me try to implement that.

**Comment by rwols** [comment]
test flakiness

**Comment by rwols** [comment]
@AmjadHD just to be sure because we're not decoding with UTF-16 anymore (but with cp1252 as you reported on Discord), does this actually for you now?

**Comment by AmjadHD** [comment]
The problem was fixed, but some characters are no shown correctly:
`server: Informationÿ: impossible de trouver des fichiers pour le(s) modŠle(s) sp‚cifi‚(s).`
it should look like:
`server: Information: impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).`

**Comment by tomv564** [comment]
Looks like the preferred encoding is misleading, and UTF-16 was the likely best fallback (in Windows). Can we change the client to read stderr as UTF-16 as soon as a UTF-8 decode fails?

**Comment by AmjadHD** [comment]
tried:
```diff
diff --git a/plugin/core/process.py b/plugin/core/process.py
index da0122c..0c2060e 100644
--- a/plugin/core/process.py
+++ b/plugin/core/process.py
@@ -71,7 +71,7 @@ def log_stream(process: 'subprocess.Popen', stream: 'IO[Any]') -> None:
             if not content:
                 break
             try:
-                decoded = content.decode("UTF-8")
+                decoded = content.decode("UTF-16")
             except UnicodeDecodeError:
                 # todo: do we still need this ?
                 decoded = content  # type: ignore
```
and I get this:
```湉潦浲瑡潩ｮ›浩潰獳扩敬搠⁥牴畯敶⁲敤⁳楦档敩獲瀠畯⁲敬猨 潭詤敬猨 灳掂晩艩猨⸩਍:```

**Comment by rwols** [comment]
@AmjadHD To rule out the possibility of SublimeText setting the wrong locale in Windows, can you open a Powershell command prompt and run the following?

```
[System.Text.Encoding]::Default
```

https://superuser.com/questions/670197/finding-out-the-default-character-encoding-in-windows

**Comment by AmjadHD** [comment]
```
PS C:\Users\Lehdhili> [System.Text.Encoding]::Default

Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```

**Comment by rwols** [comment]
This confuses me even more :+1:

**Comment by rwols** [comment]
So, the language server can choose whatever encoding it wants. It *should* use UTF-8 because payloads are in UTF-8, and otherwise *should* use the default system locale. It should not matter which language server we're looking at, but to get more context which language server are you using @AmjadHD?

I am also interested in the following:

1. What is your system locale? Run the following in Powershell: `Get-UICulture` https://serverfault.com/questions/173630/how-to-get-system-locale-in-windows-7-cmd
2. If you run Python in a REPL from the command-line (so not from within SublimeText), what does `import locale; locale.getpreferredencoding()` print?

**Comment by tomv564** [comment]
From the issue:
```
LSP: starting ['typescript-language-server.cmd', '--stdio']
```

I also read somewhere that windows console's default encoding is UTF-16, so the use of a `.cmd` wrapper might influence the chosen encoding

**Comment by AmjadHD** [comment]
```powershell
PS C:\Users\Lehdhili> Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
1036             fr-FR            Français (France)
```
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale; locale.getpreferredencoding()
'cp1252'
```

**Comment by rwols** [comment]
Perhaps we should stick to UTF-8 and fallback to locale.getpreferredlocale() if that fails.

If a French person using cp1252 is working for a Chinese customer, working on filenames with Chinese characters in it, then pretty much all logging through stderr would fail if using locale.getpreferredlocale().
On the other hand, UTF-8 can handle both French and Chinese.

I'm guessing we don't want another setting in LSP.sublime-settings for this.

So I propose:
1. Decode as UTF-8.
2. If that fails, decode as locale.getpreferredencoding().
3. If that fails, print a decoding error message.

The strange characters from @AmjadHD 's example are unfortunate but somewhat readable nonetheless, in contrast to using UTF-16.

I've also looked at the logging code of typescript-language-server

https://github.com/theia-ide/typescript-language-server/blob/f5fccedf1369b7e8db9f6b11d3a8427bcadf42b2/server/src/logger.ts#L60-L82

but I don't see anything standing out as strange.

**Comment by AmjadHD** [comment]
I like 2, raw bytes is more readable than the output of `decode('utf-8', 'ignore')`

**Comment by rwols** [comment]
But we have to convert to a string at *some* point though. We want to prefix the message with the server name. Theoretically speaking we could convert the server prefix to bytes then, as it's probably an ASCII name.

There's a third option called `'replace'`:

```
>>> print(b'Information\xff: impossible de trouver des fichiers pour le(s) mod\x8ale(s) sp\x82cifi\x82(s).\r\n'.decode('utf-8', 'replace'))
Information�: impossible de trouver des fichiers pour le(s) mod�le(s) sp�cifi�(s).
```

**Comment by tomv564** [comment]
I like replace, best of both worlds!

**Pull request merged**
