### PR TITLE
WIP: Open diagnostics panel on save/publish

### PR DESCRIPTION
**Pull request by tomv564**
An implementation to investigate #381.
Rather than opening the panel when diagnostics arrive - show the panel when the user has saved.
As relevant diagnostics can have arrived or still be pending at save, a bit of tracking state is needed.
Note: It turns out on_post_save_async is invoked even if the view was not dirty, additional check had to be added for is_dirty.

Unsolved:
- [x] The panel should probably show when the view is opened
- [ ] Add setting that combines logically with the existing `auto_show_diagnostics_panel` (default True)
- [x] Think of how to handle diagnostics for files that are not opened.

### CODE REVIEW

**Comment by tomv564** [comment]
At this point the implementation only shows the panel if the current file has diagnostics.
This is probably fine/expected for people used to single-file linters.

But servers that run compilation/type checking will probably report errors in related files that are not open yet. I believe the panel should also open for these cases: If I comment out a function in file B, I want the panel to pop up saying "file A cannot import this function".

**Comment by rmccue** [comment]
@tomv564 Alas, I switched to VS Code, so no longer use Sublime/LSP. Sorry! :)

**Comment by predragnikolic** [comment]
Initial impression is good :) great job 

But I will be using this tomorrow the whole day and see if I encounter something unexpected and give you my feedback

**Comment by predragnikolic** [comment]
Everything seems ok :)
It shows the diagnostics panel on save.

One possible improvement, but not related to this card:

I am in a file`src/hello.js`. 
Whenever the diagnostics panel open,
we should scroll the diagnostics panel view port to the currently open file section, 
in this case `◌ src/hello.js`.  
And only scroll to the section, if the file exist in the panel. 

But that can be done in a different PR. :)

**Pull request closed without merging**
