### PR TITLE
Fix: log_stderr didn't work anymore

### PR DESCRIPTION
**Pull request by rwols**

### CODE REVIEW

**Comment by rwols** [comment]
What's up with these unit tests?

**Comment by tomv564** [comment]
There are two sets of tests now: unit tests which run outside of sublime, and functional tests using UnitTesting.

You cannot import modules using the sublime API (eg settings) in unit-tested code. It needs to be passed in instead if we want to keep the option configurable. I’ve also been tempted to remove settings if the default is likely to suit everyone

**Comment by tomv564** [comment]
Thanks, please ignore my earlier comment about the unit tests. Had I looked at the failure in travis, I could have helped you with the simple fix.

**Comment by rwols** [comment]
Thanks for the fix! I don't have much time during regular weekdays, but wanted to dig into the unit test stuff this weekend.

**Pull request merged**
