### PR TITLE
Add configuration for gopls

### PR DESCRIPTION
**Pull request by frou**
There is an official Go language server taking shape: https://github.com/golang/go/wiki/gopls

### CODE REVIEW

**Comment by tomv564** [comment]
Thanks! Would be nice to help go developers choose and install this new version if it improves over the existing one.

**Comment by frou** [comment]
gopls is still in flux, but completions/hover/goto-definition seem to work quite well just now (including being able to jump all the way into stdlib source files with goto-definition!). After the next release of this package, I'll edit their wiki page to mention Sublime

**Comment by rwols** [comment]
Does signature help work as expected?

**Comment by frou** [comment]
@rwols The popup with the appropriately underlined parameter works (apart from a varargs final parameter, e.g. `xs ...T`). I may not be aware of all capabilities of Signature Help though

**Comment by frou** [comment]
I've updated their wiki to mention Sublime+LSP:

https://github.com/golang/go/wiki/gopls#integration-with-your-text-editor

(Look at the amount of fragmentation for Vim and Vim-likes!)

**Pull request merged**
