### PR TITLE
Add diagnostics count to statusbar

### LINKED ISSUE #186: Error panel pops up too fast
I'm finding that the error pane is popping up as I'm in the middle of typing a phrase. Obviously while the line is unfinished, the syntax is not correct, that's just distracting. As such, I think it would be helpful to add some kind of delay before triggering the error popup panel. Even better would be to make the delay configurable.

### PR DESCRIPTION
**Pull request by predragnikolic**
closes #186 

### CHANGED
- changed the default value for `auto_show_diagnostics_panel` to false,
- before `auto_show_diagnostics_panel` was responsible for automatically opening and closing the diagnostics panel,
now it is responsible only for opening, as the panel will automatically close when there are no errors(no need to show an empty panel),
- updated the docs for the settings I changed and added.

### ADDED
- new setting for configuring the visibility of the count in the status bar `show_diagnostics_count_in_view_status`, defaults to true,
- added diagnostics count to the status bar.

Waiting for feedback, if you have something you would change, or reject, please say so.. :)

### CODE REVIEW

**Comment by predragnikolic** [comment]
Messed up the commit history, that's why I closed it. Tried to get it in order, but didn't succeed. 

Sorry for the boder :-)

**Comment by predragnikolic** [comment]
Ok Tom :) 

Have you any suggestion on how to avoid looping over diagnostics?

**Comment by tomv564** [comment]
Sorry, I really haven't had time to have a closer look. Tested it last night, merged it now, going to add some small fixes in master. Nicely done!

**Comment by predragnikolic** [comment]
Thank you Tom :)

**Pull request merged**
