### PR TITLE
Make view.file_name() optional in stub, fix all references

### LINKED ISSUE #141: LSP crashes on unsaved files.
1. Open a new file.
2. Set Syntax to one of the supported ones.
3. Paste some code.
4. Move mouse over keywords.

```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 625, in on_hover
    vel.on_hover(point, hover_zone)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1924, in on_hover
    self.request_symbol_hover(point)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1934, in request_symbol_hover
    Request.hover(get_document_position(self.view, point)),
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1880, in get_document_position
    d['textDocument'] = {"uri": filename_to_uri(view.file_name())}
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 885, in filename_to_uri
    return urljoin('file:', pathname2url(path))
  File "./python3.3/nturl2path.py", line 46, in pathname2url
TypeError: argument of type 'NoneType' is not iterable
```

Another situation is closing an unsaved file, which creates following traceback:

```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Apps\Sublime\sublime_plugin.py", line 452, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 2460, in on_close
    Events.publish("view.on_close", view)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1908, in publish
    listener(*args)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1684, in remove_diagnostics
    if not window.find_open_file(view.file_name()):
  File "C:\Apps\Sublime\sublime.py", line 315, in find_open_file
    view_id = sublime_api.window_find_open_file(self.window_id, fname)
TypeError: String required
```

### PR DESCRIPTION
**Pull request by tomv564**
Should fix #141

### CODE REVIEW

**Comment by deathaxe** [comment]
Quite a bunch of changes required here. I was thinking about whether it was sufficient to check `view.file_name()` in the `client_for_view()` function, but it seems far away.

Some hover event is not caught right now.

```
LSP: request 5: textDocument/hover 
LSP: got json:  {"error":{"code":-32000,"message":"Server error","data":{"type":"TypeError","args":["'NoneType' object is not subscriptable"],"message":"'NoneType' object is not subscriptable"}},"id":5,"jsonrpc":"2.0 ...
LSP: Got error from server:  {'code': -32000, 'message': 'Server error', 'data': {'message': "'NoneType' object is not subscriptable", 'args': ["'NoneType' object is not subscriptable"], 'type': 'TypeError'}}
```

**Comment by tomv564** [comment]
Ah, that is at least not a `TypeError` in LSP :)
Added some more typing to uncover `None` being passed in.

**Comment by deathaxe** [comment]
Your latest changes fix the issue. If I interpret the changes correctly, most checks are added to event listeners. I am wondering, whether one could add the file_name() checks directly to ST's event listener classes and just prevent them from calling Event.publish() at all? The `DocumentSyncListener` even does it for some events right now. Maybe this could reduce the amount of required checks?

**Comment by tomv564** [comment]
Worth a try! Beware that mypy may not understand that *this time, view.file_name() is safe because I checked in the constructor that it will exist for this view*

**Pull request merged**
