### PR TITLE
fix(hover): fix typo

### PR DESCRIPTION
**Pull request by kud**
😬

### CODE REVIEW

**Comment by tomv564** [comment]
Don't worry about the failed test, looks like it's flaky. Thanks!

**Comment by kud** [comment]
👍🏻 thanks!

**Comment by kud** [comment]
How long it takes to be on package control? I mean, when will I see this change on my Sublime Text?

**Comment by tomv564** [comment]
It will take between a few days to a few weeks - want to accumulate enough
changes to warrant  the overhead of doing a release.

**Comment by kud** [comment]
Alright, thank you @tomv564 !

**Comment by tomv564** [comment]
Still collecting some fixes to do a minor release soon!

**Comment by kud** [comment]
Alright, great!

**Pull request merged**
